import type {
  EntityCapabilities,
  EntityDefinition,
  EntityGroupId,
} from "@/lib/admin-types";

export const ENTITY_GROUPS: Record<
  EntityGroupId,
  { label: string; description: string }
> = {
  accounts: {
    label: "Accounts",
    description: "Registered students, profile state, and CR assignments.",
  },
  academic: {
    label: "Academic",
    description: "University structure, courses, batches, and offerings.",
  },
  attendance: {
    label: "Attendance",
    description: "Class sessions, attendance, corrections, and reports.",
  },
  content: {
    label: "Schedules & content",
    description: "Schedules, exams, notices, resources, and communications.",
  },
  workflows: {
    label: "Workflows",
    description: "Requests and administrative review queues.",
  },
  campus: {
    label: "Campus services",
    description: "Transport, blood help, lost and found, and responses.",
  },
  system: {
    label: "System & reporting",
    description: "Immutable logs and database reporting views.",
  },
};

const definitions = [
  {
    name: "profiles",
    label: "Student profiles",
    singular: "profile",
    group: "accounts",
    description: "Application profiles linked one-to-one with Supabase Auth users.",
    searchColumns: ["full_name", "email", "student_id", "roll", "phone"],
    preferredColumns: [
      "full_name",
      "email",
      "student_id",
      "role",
      "status",
      "department_id",
      "batch_id",
      "created_at",
    ],
    defaultSort: "created_at",
    defaultDirection: "desc",
    capabilities: { create: false, delete: false },
    lockedColumns: ["id", "role", "email"],
  },
  {
    name: "cr_assignments",
    label: "CR assignments",
    singular: "CR assignment",
    group: "accounts",
    description: "Active class-representative appointments. Managed transactionally.",
    searchColumns: [],
    preferredColumns: ["profile_id", "batch_id", "assigned_by", "created_at"],
    defaultSort: "created_at",
    defaultDirection: "desc",
    managedRoute: "/cr-management",
    capabilities: { create: false, update: false, delete: false },
  },
  {
    name: "faculties",
    label: "Faculties",
    singular: "faculty",
    group: "academic",
    description: "Top-level academic faculties.",
    searchColumns: ["name", "name_bn", "code"],
    preferredColumns: ["name", "name_bn", "code", "updated_at"],
    defaultSort: "name",
  },
  {
    name: "departments",
    label: "Departments",
    singular: "department",
    group: "academic",
    description: "Departments belonging to faculties.",
    searchColumns: ["name", "name_bn", "code"],
    preferredColumns: ["name", "name_bn", "code", "faculty_id", "updated_at"],
    defaultSort: "name",
  },
  {
    name: "programs",
    label: "Programs",
    singular: "program",
    group: "academic",
    description: "Degree programs and their fixed academic systems.",
    searchColumns: ["name", "name_bn", "code"],
    preferredColumns: [
      "name",
      "code",
      "department_id",
      "academic_system",
      "total_terms",
      "updated_at",
    ],
    defaultSort: "name",
    updateLockedColumns: ["academic_system"],
  },
  {
    name: "batches",
    label: "Batches",
    singular: "batch",
    group: "academic",
    description: "Admission cohorts, current terms, and lifecycle state.",
    searchColumns: ["name", "session"],
    preferredColumns: [
      "name",
      "session",
      "admission_year",
      "program_id",
      "current_term",
      "status",
      "updated_at",
    ],
    defaultSort: "admission_year",
    defaultDirection: "desc",
    capabilities: { delete: false },
    updateLockedColumns: ["current_term", "status"],
  },
  {
    name: "courses",
    label: "Courses",
    singular: "course",
    group: "academic",
    description: "Department course catalogue.",
    searchColumns: ["code", "title", "title_bn"],
    preferredColumns: [
      "code",
      "title",
      "department_id",
      "credit_hours",
      "term_number",
      "deleted_at",
    ],
    defaultSort: "code",
    softDelete: true,
  },
  {
    name: "course_offerings",
    label: "Course offerings",
    singular: "course offering",
    group: "academic",
    description: "Courses taught to a batch in a particular term.",
    searchColumns: ["teacher_name"],
    preferredColumns: [
      "course_id",
      "batch_id",
      "term_number",
      "teacher_name",
      "deleted_at",
      "updated_at",
    ],
    defaultSort: "created_at",
    defaultDirection: "desc",
    softDelete: true,
  },
  {
    name: "class_sessions",
    label: "Class sessions",
    singular: "class session",
    group: "attendance",
    description: "Individual class meetings used for attendance.",
    searchColumns: ["topic"],
    preferredColumns: [
      "session_date",
      "start_time",
      "end_time",
      "topic",
      "offering_id",
      "batch_id",
      "deleted_at",
    ],
    defaultSort: "session_date",
    defaultDirection: "desc",
    softDelete: true,
  },
  {
    name: "attendance_records",
    label: "Attendance records",
    singular: "attendance record",
    group: "attendance",
    description: "Present or absent status for one student and class session.",
    searchColumns: [],
    preferredColumns: [
      "student_id",
      "session_id",
      "batch_id",
      "status",
      "recorded_by",
      "updated_at",
    ],
    defaultSort: "updated_at",
    defaultDirection: "desc",
    capabilities: { delete: false },
  },
  {
    name: "attendance_correction_requests",
    label: "Correction requests",
    singular: "correction request",
    group: "attendance",
    description: "Student requests to correct an attendance record.",
    searchColumns: ["reason"],
    preferredColumns: [
      "student_id",
      "session_id",
      "requested_status",
      "reason",
      "status",
      "reviewed_by",
      "created_at",
    ],
    defaultSort: "created_at",
    defaultDirection: "desc",
    lockedColumns: ["status", "reviewed_by", "reviewed_at"],
    updateLockedColumns: [
      "record_id",
      "session_id",
      "student_id",
      "batch_id",
      "requested_status",
    ],
  },
  {
    name: "attendance_history",
    label: "Attendance history",
    singular: "history event",
    group: "attendance",
    description: "Trigger-generated immutable history of attendance changes.",
    searchColumns: [],
    preferredColumns: [
      "record_id",
      "old_status",
      "new_status",
      "changed_by",
      "changed_at",
    ],
    defaultSort: "changed_at",
    defaultDirection: "desc",
    readOnly: true,
  },
  {
    name: "attendance_summary",
    label: "Attendance summary",
    singular: "attendance summary",
    group: "attendance",
    description: "Read-only course-level attendance reporting view.",
    searchColumns: [],
    preferredColumns: [
      "student_id",
      "course_code",
      "course_title",
      "total_classes",
      "present_count",
      "absent_count",
      "attendance_percentage",
    ],
    defaultSort: "student_id",
    readOnly: true,
  },
  {
    name: "class_schedules",
    label: "Class schedules",
    singular: "schedule entry",
    group: "content",
    description: "One-time, rescheduled, cancelled, and online class entries.",
    searchColumns: ["room", "building_floor", "teacher_name", "note"],
    preferredColumns: [
      "schedule_date",
      "start_time",
      "end_time",
      "type",
      "batch_id",
      "room",
      "teacher_name",
      "deleted_at",
    ],
    defaultSort: "schedule_date",
    defaultDirection: "desc",
    softDelete: true,
  },
  {
    name: "exams",
    label: "Exams",
    singular: "exam",
    group: "content",
    description: "Exam routines, notices, rooms, and timing.",
    searchColumns: ["title", "title_bn", "description", "room"],
    preferredColumns: [
      "title",
      "type",
      "exam_date",
      "start_time",
      "batch_id",
      "offering_id",
      "room",
      "deleted_at",
    ],
    defaultSort: "exam_date",
    defaultDirection: "desc",
    softDelete: true,
  },
  {
    name: "notices",
    label: "Notices",
    singular: "notice",
    group: "content",
    description: "University and batch notices with publishing workflow.",
    searchColumns: ["title", "title_bn", "body", "body_bn"],
    preferredColumns: [
      "title",
      "scope",
      "batch_id",
      "category",
      "state",
      "priority",
      "is_pinned",
      "publish_at",
      "deleted_at",
    ],
    defaultSort: "created_at",
    defaultDirection: "desc",
    softDelete: true,
  },
  {
    name: "notice_attachments",
    label: "Notice attachments",
    singular: "notice attachment",
    group: "content",
    description: "File and external-link metadata attached to notices.",
    searchColumns: ["file_name", "mime_type", "storage_path", "external_url"],
    preferredColumns: [
      "file_name",
      "notice_id",
      "mime_type",
      "size_bytes",
      "storage_path",
      "external_url",
      "created_at",
    ],
    defaultSort: "created_at",
    defaultDirection: "desc",
  },
  {
    name: "notice_reads",
    label: "Notice receipts",
    singular: "notice receipt",
    group: "content",
    description: "Notice read and acknowledgement state.",
    searchColumns: [],
    preferredColumns: ["notice_id", "profile_id", "read_at", "acknowledged"],
    defaultSort: "read_at",
    defaultDirection: "desc",
  },
  {
    name: "resources",
    label: "Resources",
    singular: "resource",
    group: "content",
    description: "Batch learning resources and link/file metadata.",
    searchColumns: ["title", "description", "file_name", "external_url"],
    preferredColumns: [
      "title",
      "type",
      "batch_id",
      "offering_id",
      "file_name",
      "external_url",
      "deleted_at",
    ],
    defaultSort: "created_at",
    defaultDirection: "desc",
    softDelete: true,
  },
  {
    name: "alerts",
    label: "Alerts",
    singular: "alert",
    group: "content",
    description: "University-wide activity feed items.",
    searchColumns: ["title", "subtitle"],
    preferredColumns: ["title", "subtitle", "type", "created_by", "created_at"],
    defaultSort: "created_at",
    defaultDirection: "desc",
  },
  {
    name: "notifications",
    label: "Notifications",
    singular: "notification",
    group: "content",
    description: "Per-recipient in-app and push notification rows.",
    searchColumns: ["title", "body", "entity_type"],
    preferredColumns: [
      "recipient_id",
      "channel",
      "title",
      "entity_type",
      "is_read",
      "read_at",
      "created_at",
    ],
    defaultSort: "created_at",
    defaultDirection: "desc",
  },
  {
    name: "batch_change_requests",
    label: "Batch change requests",
    singular: "batch change request",
    group: "workflows",
    description: "Student batch-transfer requests and review state.",
    searchColumns: ["reason"],
    preferredColumns: [
      "student_id",
      "from_batch_id",
      "to_batch_id",
      "reason",
      "status",
      "reviewed_by",
      "created_at",
    ],
    defaultSort: "created_at",
    defaultDirection: "desc",
    lockedColumns: ["status", "reviewed_by", "reviewed_at"],
    updateLockedColumns: ["student_id", "from_batch_id", "to_batch_id"],
  },
  {
    name: "bus_routes",
    label: "Bus routes",
    singular: "bus route",
    group: "campus",
    description: "Student and teacher transport routes.",
    searchColumns: ["name", "name_bn", "description", "manager_info"],
    preferredColumns: [
      "name",
      "name_bn",
      "category",
      "window_label",
      "frequency",
      "sort_order",
      "updated_at",
    ],
    defaultSort: "sort_order",
  },
  {
    name: "bus_trips",
    label: "Bus trips",
    singular: "bus trip",
    group: "campus",
    description: "Individual departures belonging to bus routes.",
    searchColumns: [
      "departure_place",
      "departure_place_bn",
      "depart_time",
      "bus_name",
    ],
    preferredColumns: [
      "route_id",
      "departure_place",
      "departure_place_bn",
      "depart_time",
      "bus_name",
      "sort_order",
    ],
    defaultSort: "sort_order",
  },
  {
    name: "bus_route_favorites",
    label: "Route favourites",
    singular: "route favourite",
    group: "campus",
    description: "Per-user favourite bus routes.",
    searchColumns: [],
    preferredColumns: ["profile_id", "route_id", "created_at"],
    defaultSort: "created_at",
    defaultDirection: "desc",
  },
  {
    name: "blood_requests",
    label: "Blood requests",
    singular: "blood request",
    group: "campus",
    description: "University blood requests and fulfilment status.",
    searchColumns: ["contact", "location", "note"],
    preferredColumns: [
      "blood_group",
      "units",
      "is_urgent",
      "status",
      "location",
      "contact",
      "requester_id",
      "created_at",
    ],
    defaultSort: "created_at",
    defaultDirection: "desc",
  },
  {
    name: "blood_donors",
    label: "Blood donors",
    singular: "blood donor",
    group: "campus",
    description: "Donor directory and current availability.",
    searchColumns: ["contact"],
    preferredColumns: [
      "profile_id",
      "blood_group",
      "contact",
      "last_donated",
      "available",
      "updated_at",
    ],
    defaultSort: "updated_at",
    defaultDirection: "desc",
  },
  {
    name: "blood_request_responses",
    label: "Blood responses",
    singular: "blood response",
    group: "campus",
    description: "Private responses sent to blood requesters.",
    searchColumns: ["message", "contact"],
    preferredColumns: [
      "request_id",
      "responder_id",
      "message",
      "contact",
      "created_at",
    ],
    defaultSort: "created_at",
    defaultDirection: "desc",
  },
  {
    name: "lost_found_items",
    label: "Lost & found items",
    singular: "lost or found item",
    group: "campus",
    description: "Reported lost/found items and moderation status.",
    searchColumns: ["title", "description", "location"],
    preferredColumns: [
      "type",
      "title",
      "location",
      "status",
      "reporter_id",
      "image_path",
      "created_at",
    ],
    defaultSort: "created_at",
    defaultDirection: "desc",
  },
  {
    name: "lost_found_responses",
    label: "Lost & found responses",
    singular: "lost and found response",
    group: "campus",
    description: "Private responses sent to item reporters.",
    searchColumns: ["message", "contact"],
    preferredColumns: ["item_id", "responder_id", "message", "contact", "created_at"],
    defaultSort: "created_at",
    defaultDirection: "desc",
  },
  {
    name: "audit_logs",
    label: "Audit logs",
    singular: "audit event",
    group: "system",
    description: "Immutable record of privileged operations.",
    searchColumns: ["action", "entity_type"],
    preferredColumns: [
      "created_at",
      "actor_id",
      "action",
      "entity_type",
      "entity_id",
      "old_data",
      "new_data",
    ],
    defaultSort: "created_at",
    defaultDirection: "desc",
    readOnly: true,
  },
  {
    name: "people_directory",
    label: "People directory",
    singular: "directory entry",
    group: "system",
    description: "Privacy-limited, read-only university directory view.",
    searchColumns: ["full_name", "email", "department_name", "faculty_name"],
    preferredColumns: [
      "full_name",
      "email",
      "department_name",
      "faculty_name",
    ],
    defaultSort: "full_name",
    readOnly: true,
  },
] satisfies EntityDefinition[];

export const ENTITIES: EntityDefinition[] = definitions;

export const ENTITY_BY_NAME = new Map(
  ENTITIES.map((definition) => [definition.name, definition]),
);

export function entitiesForGroup(group: EntityGroupId): EntityDefinition[] {
  return ENTITIES.filter((definition) => definition.group === group);
}

export function capabilitiesFor(
  definition: EntityDefinition,
): EntityCapabilities {
  if (definition.readOnly) {
    return { create: false, update: false, delete: false };
  }

  return {
    create: definition.capabilities?.create ?? true,
    update: definition.capabilities?.update ?? true,
    // Tables designed around deleted_at use archive/restore as their Delete
    // operation. Hard delete stays unavailable unless a relation explicitly
    // opts in, preserving dependent academic history.
    delete: definition.capabilities?.delete ?? !definition.softDelete,
  };
}
